### ISSUE TITLE
Exception in thread "main" java.io.IOException: Mkdirs failed to create...

### ISSUE THREAD

**Issue by yangboz** [sozykin/mipr#2]
Exception in thread "main" java.io.IOException: Mkdirs failed to create /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/hadoop-unjar7560830407203462827/META-INF/license
	at org.apache.hadoop.util.RunJar.ensureDirectory(RunJar.java:128)
	at org.apache.hadoop.util.RunJar.unJar(RunJar.java:104)
	at org.apache.hadoop.util.RunJar.unJar(RunJar.java:81)
	at org.apache.hadoop.util.RunJar.run(RunJar.java:209)
	at org.apache.hadoop.util.RunJar.main(RunJar.java:136)

**Comment by yangboz** [comment]
Only thrown in MacOS, and solution is:

@see: http://stackoverflow.com/questions/10522835/hadoop-java-io-ioexception-mkdirs-failed-to-create-some-path

1.modify jar
$ zip -d mipr-core-0.1-jar-with-dependencies.jar META-INF/LICENSE  
$ zip -d mipr-core-0.1-jar-with-dependencies.jar LICENSE

2.with grep all 
$ jar -tvf mipr-core-0.1-jar-with-dependencies.jar |grep META-INF/LICENSE

**Comment by Serob** [comment]
Same in windows also.
